name: Create Release

on:
  push:
    tags:
      - 'v[0-9]+'

permissions:
  contents: read
  issues: write

jobs:
  run-tests:
    uses: ./.github/workflows/test.yml

  create_release:
    needs: run-tests
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get information from tag
        id: info
        run: |
          previousTag=$(git --no-pager tag --sort=creatordate --merged ${{ github.ref_name }} | tail -2 | head -1)
          echo "currentTag=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          echo "previousTag=${previousTag}" >> $GITHUB_OUTPUT
          echo "author=${{ github.actor }}" >> $GITHUB_OUTPUT
          echo "date=$(date +'%d.%m.%Y %H:%M:%S')" >> $GITHUB_OUTPUT

      - name: Changelog
        uses: ardalanamini/auto-changelog@v4
        id: changelog
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          commit-types: |
            feat    : New Features
            fix     : Bug Fixes
            build   : Build System & Dependencies
            perf    : Performance Improvements
            docs    : Documentation
            test    : Tests
            refactor: Refactors
            chore   : Chores
            ci      : CI
            style   : Code Style
            revert  : Reverts
          default-commit-type     : Other Changes
          mention-authors         : true
          mention-new-contributors: true
          include-compare-link    : true
          include-pr-links        : true
          include-commit-links    : true
          semver                  : false
          use-github-autolink     : true

      - name: Create or update issue
        id: issue
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHANGELOG: ${{ steps.changelog.outputs.changelog }}
          TAG: ${{ steps.info.outputs.currentTag}}
          AUTHOR: ${{ steps.info.outputs.author }}
          DATE: ${{ steps.info.outputs.date }}
        with:
          filename: .github/ISSUE_TEMPLATE.md
          update_existing: true
          search_existing: all

      - name: Comment issue with test results
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ steps.issue.outputs.number }}
          body: |
            Download test results:
            ${{github.server_url}}/${{ github.repository }}/actions/runs/${{github.run_id}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    outputs:
      issueNumber: ${{ steps.issue.outputs.number }}
  
  build-and-deploy:
    needs: [create_release]
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Create release branch
        run: |
          git checkout -b release-${{ github.ref_name }}
          git push -u origin release-${{ github.ref_name }}

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install and Build
        run: |
          npm ci
          PUBLIC_URL="/shri-ci-task" npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build

      - name: Comment Issue
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ needs.create_release.outputs.issueNumber }}
          body: |
            Deploy ${{ github.run_id }}

            Deploy Link: https://ilyamolokov.github.io/shri-ci-task
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Close Issue
        uses: peter-evans/close-issue@v3
        with:
          issue-number: ${{ needs.create_release.outputs.issueNumber }}
          comment: |
            Close Issue
            Issue automatically closed
